# Generated by Django 4.1.5 on 2023-01-29 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("westudy", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="date_of_birth",
            field=models.DateField(null=True),
        ),
    ]
