# Generated by Django 4.1.5 on 2023-05-13 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("westudy", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shifts",
            name="weekday",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
