# Generated by Django 4.1.5 on 2023-04-13 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("westudy", "0002_course_number_of_stars"),
    ]

    operations = [
        migrations.CreateModel(
            name="Shifts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shift", models.CharField(max_length=100)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
            ],
        ),
        migrations.AddField(
            model_name="course",
            name="shifts",
            field=models.ManyToManyField(related_name="shifts", to="westudy.shifts"),
        ),
    ]
