# Generated by Django 4.1.5 on 2023-04-13 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("westudy", "0003_shifts_course_shifts"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="completion_time",
        ),
        migrations.RemoveField(
            model_name="course",
            name="start_time",
        ),
    ]
