# Generated by Django 4.1.5 on 2023-05-14 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("westudy", "0003_alter_course_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="numer_of_months",
            field=models.IntegerField(null=True),
        ),
    ]
