# Generated by Django 4.1.5 on 2023-04-13 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("westudy", "0004_remove_course_completion_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shifts",
            name="shift",
            field=models.CharField(default="No shift", max_length=100, null=True),
        ),
    ]
