# Generated by Django 4.1.5 on 2023-01-30 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("westudy", "0004_rename_unisersity_university"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("number_of_courses", models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("program_type", models.CharField(max_length=100)),
                (
                    "background_image",
                    models.ImageField(
                        blank="", default="", null=True, upload_to="background/"
                    ),
                ),
                ("institution", models.CharField(max_length=100)),
                ("requirements", models.BooleanField(default=False)),
                ("start_of_course", models.DateField(null=True)),
                ("end_of_course", models.DateField(null=True)),
                ("start_time", models.CharField(max_length=100)),
                ("completion_time", models.CharField(max_length=100)),
                (
                    "discount",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                ("country", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("language", models.CharField(max_length=100)),
                ("number_of_teachers", models.IntegerField(null=True)),
                ("accept_installments", models.BooleanField(default=False)),
                (
                    "category",
                    models.ManyToManyField(
                        null=True, related_name="category", to="westudy.category"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Modality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="TypeOfProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="profile",
            field=models.ImageField(
                blank="", default="", null=True, upload_to="profile/"
            ),
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "course",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="westudy.course",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="course",
            name="course_modalities",
            field=models.ManyToManyField(
                null=True, related_name="course_modalities", to="westudy.modality"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="modality",
            field=models.ManyToManyField(
                null=True, related_name="modality", to="westudy.modality"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="type_of_program",
            field=models.ManyToManyField(
                null=True, related_name="type_of_program", to="westudy.typeofprogram"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="university",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="westudy.university",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="program_preferences",
            field=models.ManyToManyField(
                null=True,
                related_name="program_preferences",
                to="westudy.typeofprogram",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="saved_courses",
            field=models.ManyToManyField(
                null=True, related_name="saved_courses", to="westudy.course"
            ),
        ),
    ]
