# Generated by Django 4.1.5 on 2023-01-30 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "westudy",
            "0005_category_course_modality_typeofprogram_user_profile_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="category",
            field=models.ManyToManyField(
                related_name="category", to="westudy.category"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="course_modalities",
            field=models.ManyToManyField(
                related_name="course_modalities", to="westudy.modality"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="modality",
            field=models.ManyToManyField(
                related_name="modality", to="westudy.modality"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="type_of_program",
            field=models.ManyToManyField(
                related_name="type_of_program", to="westudy.typeofprogram"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="program_preferences",
            field=models.ManyToManyField(
                related_name="program_preferences", to="westudy.typeofprogram"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="saved_courses",
            field=models.ManyToManyField(
                related_name="saved_courses", to="westudy.course"
            ),
        ),
    ]
