# Generated by Django 4.1.5 on 2023-04-13 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("westudy", "0005_alter_shifts_shift"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shifts",
            name="shift",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
