# Generated by Django 4.1.5 on 2023-01-31 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "westudy",
            "0006_alter_course_category_alter_course_course_modalities_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="university",
            new_name="university_id",
        ),
    ]
