# Generated by Django 4.1.5 on 2023-04-15 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("westudy", "0006_alter_shifts_shift"),
    ]

    operations = [
        migrations.AddField(
            model_name="shifts",
            name="id_unibveristy",
            field=models.IntegerField(default=0),
        ),
    ]
