# Generated by Django 4.1.5 on 2023-02-01 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("westudy", "0007_rename_university_course_university_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="university_id",
            new_name="university",
        ),
    ]
