# Generated by Django 4.1.5 on 2023-04-15 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("westudy", "0007_shifts_id_unibveristy"),
    ]

    operations = [
        migrations.RenameField(
            model_name="shifts",
            old_name="id_unibveristy",
            new_name="id_university",
        ),
    ]
