# Generated by Django 4.1.5 on 2023-04-15 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("westudy", "0008_rename_id_unibveristy_shifts_id_university"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="shifts",
        ),
        migrations.AddField(
            model_name="shifts",
            name="course",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="westudy.course",
            ),
        ),
    ]
