# Generated by Django 4.1.5 on 2023-02-03 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("westudy", "0008_rename_university_id_course_university"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="link",
            field=models.TextField(null=True),
        ),
    ]
