# Generated by Django 4.1.5 on 2023-04-15 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("westudy", "0009_remove_course_shifts_shifts_course"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Schedule",
        ),
    ]
