# Generated by Django 4.1.5 on 2023-02-03 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("westudy", "0010_remove_course_course_modalities"),
    ]

    operations = [
        migrations.AddField(
            model_name="modality",
            name="number_of_courses",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
