# Generated by Django 4.1.5 on 2023-02-03 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("westudy", "0011_modality_number_of_courses"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="modality",
            name="number_of_courses",
        ),
        migrations.AddField(
            model_name="typeofprogram",
            name="number_of_courses",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
